---
- include: tasks/oah-env-setup.yml
  when: oah_command == "env_setup"

- include: tasks/oah-create-user.yml
  when: oah_command == "create_user"

- include: tasks/oah-update-user.yml
  when: oah_command == "update_user"

- include: tasks/oah-remove-user.yml
  when: oah_command == "remove_user"

- include: tasks/oah-reset-user.yml
  when: oah_command == "reset_user"

- include: tasks/oah-validate-user.yml
  when: oah_command == "validate_user"

#- include: tasks/oah-{{ oah_command }}.yml
