---
- debug:
    msg: "oah-remove-users of oah.users"

# remove oah-user
- name: check and add oah user if OAH_USER env variable set or oah_user ansible variable is set
  user: 
    name: "{{oah_user}}" 
    state: absent
  become: true

#remove the user group
- name: Create user supplied group if does not exists
  ansible.builtin.group:
    name: "{{ oah_user_group }}"
    state: absent
  become: true
