---
- debug:
    msg: "reset of oah.users"
#remove oah user


# check and add oah user if OAH_USER env variable set or oah_user ansible variable is set

# display users created if verbose option enabled
