---
- debug:
    msg: "oah-install of oah.users"

#create user groups admin or user defined
- name: Create user supplied group if does not exists
  ansible.builtin.group:
    name: "{{ oah_user_group }}"
    state: present
  become: true

# Add oah user if OAH_USER env variable set or oah_user ansible variable is set
- name: check and add oah user if OAH_USER env variable set or oah_user ansible variable is set
  user: 
    name: "{{oah_user}}" 
    password: "{{ oah_user_pwd }}"
    group: "{{oah_user_group}}"
    generate_ssh_key: true
    state: present
  register: user_details
  when: (ansible_env.OAH_USER is not defined) or (oah_user is defined)
  become: true
    #- debug: 
    #var:  ansible_env.OAH_USER

# display users created if verbose option enabled
# 
- name: display the user data
  debug:
    var: user_details
  when: enable_verbose == true 
