---
- debug:
    msg: "remove-users"

# remove oah-user
- name: check and add oah user if OAH_USER env variable set or user ansible variable is set
  user: 
    name: "{{user}}" 
    state: absent
  become: true

#remove the user group
- name: Remove user supplied group if exists
  ansible.builtin.group:
    name: "{{ user_group }}"
    state: absent
  become: true
