---
- debug:
    msg: "reset of oah.users"

# Add oah user if OAH_USER env variable set or oah_user ansible variable is set
- name: check and add oah user if OAH_USER env variable set or oah_user ansible variable is set
  user:
    name: "{{ user }}"
    password: "admin"
    append: false
    groups: ""
    create_home: true
    generate_ssh_key: false
    home: "/home/{{ (user) }}"
    move_home: "{{ (user_home_path != '/home/' + user) | ternary(true, false)}}"
    password_expire_max: 90
    password_expire_min: 7
    password_lock: false
    seuser: "user_u"
    shell: "/bin/bash"
    umask: "0622"
    update_password: "always"
    state: present
  register: user_details
  when: (ansible_env.OAH_USER is not defined) or (user is defined)
  become: true

# display users created if verbose option enabled
# 
- name: display the user data
  debug:
    var: user_details
  when: enable_verbose == true
